### ISSUE TITLE
https://validate.puppet.com/ not working

### ISSUE THREAD

**Issue by aujla0991** [puppetlabs/puppet-validator#30]
## Describe the Bug

https://validate.puppet.com/ is not working 

503 Service Temporarily Unavailable

## Expected Behavior
Website should be functional

## Steps to Reproduce
1. Go to 'https://validate.puppet.com/'

**Comment by mcka1n** [comment]
Hey @aujla0991 

Thanks for reporting this 👍 , I'm sorry for the delay in our response to this ticket.

I just tested it and it is currently working, we might have had a temporary issue back then. I will close this ticket.
